# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ae7104424c5a6bf60fa8d31fc0903cdd43e74469d8edf60c5bbc50f5886359d79c9f86222c452ab8524b0eb1cbeeb7275e2981180dc347c89d817bc71b0721

test:
  secret_key_base: 1d4c2ee30ab47d5ec910566cbd3a0c693f98cd5bd84cd9b89317d4068162b386ed6b35f14224f3ac505f485b0b57118f849c9532e864b8c770437ea7437d28b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
