# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e4cae3cf3fd32c30ae909f34eeb311e074202be26a1877e5d6e978a1dec3e04f463d259ac790a7c3e22db4b506c62b8417eb3070d5d70740c111c7db5be9d1

test:
  secret_key_base: 900ce3efa6d39c9d4cedd6dc5106645c0ed3c24c8a60879992998f3872adb7ee7a7277411434d5a5d7046ea2249174fdfdb29e6e97e3e7b4155fc42c6d54cac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
